In [2]:
import numpy as np
import copy


In [3]:
class Dado:

    A =[[ 1,  6,  2,   4],
        [ 3, 19,  4,  15],
        [ 1,  4,  8, -12],
        [ 5, 33,  9,   3]]
            
    B = [8, 25, 18, 72]

#    solucao = [-138, 20, 11, 1]

def print_matrix(matrix):
    for i in matrix:
        print(i,)
    print("\n")

In [4]:
def lu( mA, mode = "separado"):

#    Computa a Fatoracao LU com pivoteamento parcial de uma matriz (nxn)
#    :param A: Matriz Real e Quadrada
#    :param mode:
#        1: condensado: return: Pivot, LU, Det 
#        (com LU condensada em uma unica matriz A) sendo U a matriz triangular 
#        superior mais a diagonal de A e L a matriz triangular inferior de A 
#
#        2: separado: return: Pivot, L, U, Det 
#        (com LU separada em uma matriz L e outra U)


    print("Fazendo a decomposica LU")

    if mode == "separado": 
        print("\t Retorna: P L U Det, com LU separada em uma matriz L e outra U")
    elif mode == "condensado": 
        print("\t Retorna P LU Det, com LU condensada em uma unica matriz")
    else: raise Exception("Modo especificado incorretamente")

    A = copy.deepcopy(mA)
    n = len(A)
    pivot = np.zeros(n, int)
    for i in range(n):
        pivot[i] = i

    det = np.int64(1)
    for j in range(0, n-1):
        #escolha do elemento pivot

        p = j
        amax = abs(A[j][j])

        for k in range(j+1, n):
            if abs(A[k][j]) > amax:
                amax = abs(A[k][j])
                p = k

        if p != j: 

            for k in range(0, n): # troca de linhas
                A[j][k], A[p][k] = A[p][k], A[j][k]
        
            pivot[j], pivot[p] = pivot[p], pivot[j]
            det *= -1

        det *= A[j][j]

        if abs(A[k][j]) != 0:
            r =1.0 / A[j][j]

            for i in range(j+1, n):
                mult = A[i][j] * r 
                A[i][j] = mult

                for k in range(j+1, n):
                    A[i][k] -= mult * A[j][k]

    det *= A[n-1][n-1]

    if mode == "separado":
        L = np.identity(n)
        U = np.zeros((n,n))
        for i in range(n):
            U[i][i] = A [i][i]
            for j in range(i):
                L[i][j] = A[i][j]
                U[j][i] = A[j][i]
        print(pivot, '\n', L, '\n', U, '\n', det)  

    elif mode == "condensado":
        print( pivot, '\n', A, '\n', det)

    

In [5]:
lu(Dado.A, "separado")

Fazendo a decomposica LU
	 Retorna: P L U Det, com LU separada em uma matriz L e outra U
[3 2 1 0] 
 [[1.         0.         0.         0.        ]
 [0.2        1.         0.         0.        ]
 [0.6        0.30769231 1.         0.        ]
 [0.2        0.23076923 0.37209302 1.        ]] 
 [[  5.          33.           9.           3.        ]
 [  0.          -2.6          6.2        -12.6       ]
 [  0.           0.          -3.30769231  17.07692308]
 [  0.           0.           0.          -0.04651163]] 
 -1.9999999999995521
